### PR TITLE
Mac OS X specific configuration

### PR DESCRIPTION
**Pull request by aia**
Need to include /usr/local/include on Mac OS X to get librrd to build with rrdtool from Homebrew

### CODE REVIEW

**Comment by bernd** [comment]
Thank you!

So I can add MacOS X to the list of tested operating systems? Which version of OS X and ruby?

**Comment by aia** [comment]
Yes, MacOS X works.

I am on the latest Lion 10.7.2, Homebrew, RVM, Ruby 1.9.3p0

ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin11.2.0]

**Comment by aia** [comment]
Oh,
RRDtool 1.4.5  Copyright 1997-2010 by Tobias Oetiker tobi@oetiker.ch

**Comment by bernd** [comment]
Thank you! :)

**Comment by jessereynolds** [comment]
I found I had to also add "-L/usr/local/Cellar/rrdtool/1.4.5/lib" to LDFLAGS in extconf.rb otherwise the rrd dylib is not found:

```
  9 when /darwin/i                                                                                                                       
 10   puts "Mac OS X"                                                                                                                    
 11   $INCFLAGS += ' -I/usr/local/include'                                                                                               
 12   $LDFLAGS += ' -L/usr/local/Cellar/rrdtool/1.4.5/lib'                                                                               
 13 end                                                                                                                                  
```

I think the only differences between my environment and that of @aia's above is I'm on Ruby 1.9.2 and using rbenv instead of rvm. Perhaps my Homebrew isn't doing the right thing with library paths. Perhaps Homebrew have changed the RRDtool 1.4.5 package definition. Not sure.

**Comment by jessereynolds** [comment]
Or easier than messing with extconf.rb:

```
gem install librrd -- --with-rrd-dir=/usr/local/Cellar/rrdtool/1.4.5
```

**Comment by aia** [comment]
Looks like in your setup Homebrew did not add a link in /usr/local/lib

ls -al /usr/local/lib/_rrd_

lrwxr-xr-x    1 artem     wheel      42 Nov 21 23:58 librrd.4.dylib -&gt; ../Cellar/rrdtool/1.4.5/lib/librrd.4.dylib
lrwxr-xr-x    1 artem     wheel      36 Nov 21 23:58 librrd.a -&gt;  ../Cellar/rrdtool/1.4.5/lib/librrd.a
lrwxr-xr-x    1 artem     wheel      40 Nov 21 23:58 librrd.dylib -&gt;  ../Cellar/rrdtool/1.4.5/lib/librrd.dylib
lrwxr-xr-x    1 artem     wheel      45 Nov 21 23:58 librrd_th.4.dylib -&gt;  ../Cellar/rrdtool/1.4.5/lib/librrd_th.4.dylib
lrwxr-xr-x    1 artem     wheel      39 Nov 21 23:58 librrd_th.a -&gt;  ../Cellar/rrdtool/1.4.5/lib/librrd_th.a
lrwxr-xr-x    1 artem     wheel      43 Nov 21 23:58 librrd_th.dylib -&gt;  ../Cellar/rrdtool/1.4.5/lib/librrd_th.dylib

**Pull request merged**
